name: Compute user allocations

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:
    inputs:
      run_dates:
        description: 'A comma separated list of ISO dates, e.g. 2024-02-23,2024-02-24 for which to run the computation'
      overwrite:
        description: 'Whether to overwrite data for the given date if it exists'
        required: true
        options:
          - "true"
          - "false"
        default: "true"

concurrency: query

jobs:
  run:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm install

      - name: Compute distributions
        env:
          PGHOST: ${{ secrets.POSTGRES_HOST }}
          PGPORT: ${{ secrets.POSTGRES_PORT }}
          PGDATABASE: ${{ secrets.POSTGRES_DB }}
          PGUSER: ${{ secrets.POSTGRES_USERNAME }}
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          PGSSLMODE: require
          NODE_TLS_REJECT_UNAUTHORIZED: 0
          RUN_DATES: ${{ inputs.run_dates }}
          OVERWRITE: ${{ inputs.overwrite }}
        run: npm run compute-distributions
