name: Compute distributions

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:
    inputs:
      reward_periods:
        required: false
        description: "Comma delimited list of period IDs to be recomputed"
        type: string
      database:
        default: "mainnet"
        required: true
        description: "Which database to run on"
        type: choice
        options:
          - "eth_sepolia"
          - "sepolia"
          - "eth_mainnet"
          - "mainnet"

concurrency: distributions

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        database:
          - "eth_sepolia"
          - "sepolia"
          - "eth_mainnet"
          - "mainnet"

    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - run: npm install
        if: ${{ inputs.database == null || matrix.database == inputs.database }}

      - run: npm run compute-distributions
        if: ${{ inputs.database == null || matrix.database == inputs.database }}
        env:
          PGHOST: ${{ secrets.POSTGRES_HOST }}
          PGPORT: ${{ secrets.POSTGRES_PORT }}
          PGUSER: ${{ secrets.POSTGRES_USERNAME }}
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          PGDATABASE: ${{ matrix.database }}
          PGSSLMODE: require
          NODE_TLS_REJECT_UNAUTHORIZED: 0
          REWARD_PERIODS: ${{ inputs.reward_periods }}
