name: Create merkle root

on:
  schedule:
    - cron: '0 2 7,21 3 *'
  workflow_dispatch:
    inputs:
      start_date:
        description: 'The ISO format start date of the date range for which to compute the merkle root'
      end_date:
        description: 'The ISO format end date of the date range for which to compute the merkle root'

concurrency: query

jobs:
  run:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm install

      - name: Create merkle root
        env:
          PGHOST: ${{ secrets.POSTGRES_HOST }}
          PGPORT: ${{ secrets.POSTGRES_PORT }}
          PGDATABASE: ${{ secrets.POSTGRES_DB }}
          PGUSER: ${{ secrets.POSTGRES_USERNAME }}
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          START_DATE: ${{ inputs.start_date }}
          END_DATE: ${{ inputs.end_date }}
        run: npm run create-root
