name: Create voter drop

on:
  workflow_dispatch:
    inputs:
      proposal_id:
        required: true
        description: 'The` ID of the proposal for which to create the drop'
      total_reward:
        required: true
        description: 'The total reward in wei of token'

concurrency: query

jobs:
  run:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm install

      - name: Create merkle root
        env:
          PGHOST: ${{ secrets.POSTGRES_HOST }}
          PGPORT: ${{ secrets.POSTGRES_PORT }}
          PGDATABASE: ${{ secrets.POSTGRES_DB }}
          PGUSER: ${{ secrets.POSTGRES_USERNAME }}
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          PGSSLMODE: require
          NODE_TLS_REJECT_UNAUTHORIZED: 0
          PROPOSAL_ID: ${{ inputs.proposal_id }}
          TOTAL_REWARD: ${{ inputs.total_reward }}
        run: npm run create-root
