name: Deploy airdrop contract

on:
  workflow_dispatch:

concurrency: deploy-drop

jobs:
  run:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - run: npm install

      - name: Deploy drop
        env:
          PGHOST: ${{ secrets.POSTGRES_HOST }}
          PGPORT: ${{ secrets.POSTGRES_PORT }}
          # this only runs on the starknet mainnet database
          PGDATABASE: mainnet
          PGUSER: ${{ secrets.POSTGRES_USERNAME }}
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          PGSSLMODE: require
          NODE_TLS_REJECT_UNAUTHORIZED: 0
          ACCOUNT_ADDRESS: ${{ secrets.DEPLOYMENT_ACCOUNT_ADDRESS }}
          PRIVATE_KEY: ${{ secrets.DEPLOYMENT_PRIVATE_KEY }}
          NODE_URL: ${{ secrets.DEPLOYMENT_NODE_URL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: npm run deploy-airdrop-contract
