name: Generate drop

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

concurrency: query

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        include:
          - database: "eth_mainnet"
            network_type: "EVM"
          - database: "eth_sepolia"
            network_type: "EVM"
          - database: "mainnet"
            network_type: "STARKNET"
          - database: "sepolia"
            network_type: "STARKNET"

    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - run: npm install

      - name: Generate drop
        env:
          PGHOST: ${{ secrets.POSTGRES_HOST }}
          PGPORT: ${{ secrets.POSTGRES_PORT }}
          PGUSER: ${{ secrets.POSTGRES_USERNAME }}
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          PGSSLMODE: require
          NODE_TLS_REJECT_UNAUTHORIZED: 0
          PGDATABASE: ${{ matrix.database }}
          NETWORK_TYPE: ${{ matrix.network_type }}
        run: npm run generate-drop
