name: Generate drop

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

concurrency: query

jobs:
  run:

    strategy:
      fail-fast: false
      matrix:
        include:
          - database: "eth_mainnet"
            campaigns: "ekubo_dao_wave_zero"
            minimum_drop_size: "1000e18"

    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - run: npm install

      - name: Generate drop
        env:
          PGHOST: ${{ secrets.POSTGRES_HOST }}
          PGPORT: ${{ secrets.POSTGRES_PORT }}
          PGDATABASE: ${{ matrix.database }}
          PGUSER: ${{ secrets.POSTGRES_USERNAME }}
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          PGSSLMODE: require
          NODE_TLS_REJECT_UNAUTHORIZED: 0
          CAMPAIGNS: ${{ matrix.campaigns }}
          MIN_DROP_SIZE: ${{ matrix.minimum_drop_size }}
        run: npm run generate-drop
