name: Generate drop

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

concurrency: query

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        include:
          - database: "eth_mainnet"
            network_type: "EVM"
            positions_nft_address: "0xA37cc341634AFD9E0919D334606E676dbAb63E17"
          - database: "eth_sepolia"
            network_type: "EVM"
            positions_nft_address: "0xA37cc341634AFD9E0919D334606E676dbAb63E17"
          - database: "mainnet"
            network_type: "STARKNET"
            positions_nft_address: "0x07b696af58c967c1b14c9dde0ace001720635a660a8e90c565ea459345318b30"
          - database: "sepolia"
            network_type: "STARKNET"
            positions_nft_address: "0x04afc78d6fec3b122fc1f60276f074e557749df1a77a93416451be72c435120f"

    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - run: npm install

      - name: Generate drop
        env:
          PGHOST: ${{ secrets.POSTGRES_HOST }}
          PGPORT: ${{ secrets.POSTGRES_PORT }}
          PGUSER: ${{ secrets.POSTGRES_USERNAME }}
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          PGSSLMODE: require
          NODE_TLS_REJECT_UNAUTHORIZED: 0
          PGDATABASE: ${{ matrix.database }}
          NETWORK_TYPE: ${{ matrix.network_type }}
          POSITION_NFT_TOKEN_ADDRESS: ${{ matrix.positions_nft_address }}
        run: npm run generate-drop
